# Generated by Django 5.1.3 on 2024-11-22 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=20, verbose_name='病名')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200, verbose_name='病状')),
                ('telnumber', models.IntegerField(max_length=11, verbose_name='電話番号')),
                ('name', models.TextField(verbose_name='住所')),
                ('image1', models.ImageField(upload_to='history', verbose_name='イメージ１')),
                ('image2', models.ImageField(upload_to='history', verbose_name='イメージ2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='history', verbose_name='イメージ3')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pims.disease', verbose_name='病名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
