# Generated by Django 5.1.3 on 2024-11-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
