# Generated by Django 5.1.3 on 2024-11-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
