# Generated by Django 5.1.3 on 2024-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='title',
            new_name='specialist',
        ),
        migrations.AlterField(
            model_name='record',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='attachment', verbose_name='イメージ２'),
        ),
        migrations.AlterField(
            model_name='record',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='attachment', verbose_name='イメージ３'),
        ),
    ]
