# Generated by Django 5.1.3 on 2024-11-25 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0008_rename_title_specialist_specialist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
